name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:

    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x

      - name: Prepare FFMpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage" --no-restore --logger GitHubActions --logger:"console;verbosity=detailed" --results-directory /tmp/test-results/

#      - name: Report results to DeepSource
#        run: curl https://deepsource.io/cli | sh
#             ./bin/deepsource report --analyzer test-coverage --key csharp --value-file /tmp/test-results/<test_guid>/coverage.cobertura.xml
#        env:
#          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

#      - name: Report test-coverage to DeepSource
#        uses: deepsourcelabs/test-coverage-action@master
#        with:
#          key: csharp
#          coverage-file: coverage.cobertura.xml
#          dsn: ${{ secrets.DEEPSOURCE_DSN }}

#      - name: Add git safe.directory for container
#        run: |
#            mkdir -p /home/runner/work/_temp/_github_home
#            printf "[safe]\ndirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig
#
#      - name: Report test-coverage to DeepSource
#        uses: deepsourcelabs/test-coverage-action@master
#        with:
#          key: csharp
#          coverage-file: coverage.cobertura.xml
#          dsn: ${{ secrets.DEEPSOURCE_DSN }}


      - name: Report results to DeepSource
        run: curl https://deepsource.io/cli | sh
             for /r %F in (*coverage.cobertura.xml) do ./bin/deepsource report --analyzer test-coverage --key csharp --value-file %F
        shell: cmd
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
