name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:

    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x.x
      - name: Prepare FFMpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --no-restore --logger GitHubActions
